import { getServerSession } from 'next-auth/next';
import { Inter } from 'next/font/google';
import AuthProvider from './AuthProvider';
import { authOptions } from './api/auth/[...nextauth]/route';
import Nav from './components/Nav';


import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  console.log(session);
  return (
    <AuthProvider>
      <html lang='en'>
        <body>
          {/* <Nav /> */}
          <div className='main-body'>{children}</div>
        </body>
      </html>
    </AuthProvider>
  );
}
